---
apiVersion: v1
kind: Service
metadata:
  name: memberdb
  labels:
    app: memberdb
    service: memberdb
spec:
  ports:
  - port: 80
    name: http
    targetPort: 5432
  selector:
    app: memberdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberdb
  labels:
    app: memberdb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memberdb
      version: v1
  template:
    metadata:
      labels:
        app: memberdb
        version: v1
    spec:
      containers:
      - name: membermanagement
        image: 808083692205.dkr.ecr.us-east-2.amazonaws.com/memberdb:latest
        env: 
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: MemberMgt
        - name: POSTGRES_PASSWORD
          value: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
---
